version: '3.7'

services:
  am_estimator:
    container_name: am_estimator
    build: .
    ports:
      - "4003:4003"
    env_file:
      - .env
    volumes:
      - $DATA_FOLDER_EXTERNAL:$DATA_FOLDER
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]