version: '3.8'

services:
  am_interface:
    container_name: am_interface
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    command: npm start
