version: '3.7'

services:
  am_recognition:
    container_name: am_recognition
    build: .
    ports:
      - "4002:4002"
    env_file:
      - .env
    volumes:
      - $DATA_FOLDER_EXTERNAL:$DATA_FOLDER
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]